name: kenga_boo
description: Rungo App for kids.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^1.0.1
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.1.3
  cached_network_image: 3.1.0+1
  cloud_firestore: 2.5.4
  firebase_auth: 3.2.0
  firebase_core: 1.10.0
  firebase_storage: 10.1.0
  flame: ^1.0.0
  font_awesome_flutter: 8.11.0
  google_fonts: 2.1.0
  google_sign_in: 5.2.1
  image_picker: 0.8.4+4
  intl: 0.17.0
  json_path: 0.2.1
  json_serializable: 6.1.3
  mime_type: 1.0.0
  page_transition: 2.0.4
  rxdart: 0.26.0
  shared_preferences: 2.0.11
  sign_in_with_apple:
    git:
      url: https://github.com/asmengistu/dart_packages
      ref: ab18d53a80e0a4bb90f1ad84f37f1b408930f28d
      path: packages/sign_in_with_apple/sign_in_with_apple/
  timeago: 3.1.0
  url_launcher: 6.0.15


  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: 2.1.7
  built_value_generator: 8.1.3
  flutter_launcher_icons: 0.9.2

  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'


flutter:

  uses-material-design: true

  assets:
    - assets/snake_bg.png
    - assets/audios/success.mp3
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
